version: '3.8'

services:
  # Jaeger with OTLP support
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14317:14317"  # OTLP gRPC (custom port)
      - "14318:14318"  # OTLP HTTP (custom port)
      - "14250:14250"  # Jaeger gRPC
      - "14268:14268"  # Jaeger HTTP
      - "9411:9411"    # Zipkin
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_GRPC_PORT=14317
      - COLLECTOR_OTLP_HTTP_PORT=14318
