{
 "title": "gRPC Metrics Dashboard",
 "tags": [ "gRPC" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "gRPC Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total[1m])) by(grpc_method)"
    }
   ]
  },
  {
   "title": "gRPC 95th Percentile Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket[1m])) by (le, grpc_method)) * 1000"
    }
   ]
  },
  {
   "title": "gRPC Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\"}[1m])) by (grpc_method, grpc_code) / sum(rate(grpc_server_handled_total[1m])) by (grpc_method) * 100"
    }
   ]
  },
  {
   "title": "Client Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_requests_total[1m])) by (method, status)"
    }
   ]
  }
 ]
}